name: blog deploy # workflow 的名字

# 触发事件 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflow
on:  
  push:  # git push 事件
    branches:
      - main  # 指定分支

jobs:
  deploy:  # job 名字
    runs-on: ubuntu-20.04   # 运行环境，Github 提供的运行 job 的虚拟机， https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners
    steps:
      - uses: actions/checkout@v3   # 使用 github 提供的 action， 拉取代码
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo           # 步骤名字
        uses: peaceiris/actions-hugo@v2  # 安装 hugo
        with:
          hugo-version: latest
          extended: true

      - name: Build                
        run: hugo           # 执行命令 hugo 编译为静态文件

      - name: Deploy
        uses: burnett01/rsync-deployments@5.2   # 同步到服务器
        with:
          switches: -avzr --delete
          path: ./public/
          remote_path: ${{ secrets.DEPLOY_PATH }} # 远程主机目录
          remote_host: ${{ secrets.DEPLOY_HOST }} # 远程主机 IP
          remote_port: ${{ secrets.DEPLOY_PORT }} # ssh 端口，默认为 22
          remote_user: ${{ secrets.DEPLOY_USER }} # ssh user
          remote_key: ${{ secrets.DEPLOY_KEY }} # ssh 私钥
