name: Build and deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: '0.110.0'
    - name: Build
      run: hugo --minify
    - name: Deploy
      uses: appleboy/rsync-action@master
      with:
        args: -avz --delete
        src: public/
        dest: ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/path/to/your/site
      env:
        RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
