name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      # BLOG_DEPLOY_KEY 私钥名称自行修改
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}            

      # Runs a single command using the runners shell
      # 这里的 jyan.wang 是我的域名，自行修改，前提条件是域名已经解析到 ip 上
      - name: Scan public keys
        run: |
          ssh-keyscan www.liuzouyuan.com >> ~/.ssh/known_hosts          

      # Hugo setup
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13

      # hugo 构建命令，可自行修改参数
      - name: Build
        run: |
          hugo --minify          

      # deploy
      # rsync -av --delete 后面的自行修改
      - name: Deploy
        run: |
          rsync -av --delete public/ root@jyan.wang:/usr/share/nginx/html          
