name: Auto Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./public/
          remote_path: /root/y/public
          remote_host: 47.108.131.224
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.YUAN_KEY }} # 这里是 ssh 私钥，敏感数据建议设置成 secrets 获取
